### ISSUE TITLE
能不能出一个部署的教程呀

### ISSUE THREAD

**Issue by YongPengPeng** [Red-Asuka/CloudMusic#2]
我在本地的mac上面可以跑起来，但是在阿里云的centos上面就失败了

**Comment by Red-Asuka** [comment]
你好，我是直接使用node起的服务，首先将前端项目打包
根据https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/app.js 的app.js中有一段代码
// static
app.use(express.static(path.join(__dirname, 'public')))
将打包好的文件放入public文件夹下，使用forever或者pm2后台持久运行node服务
如需更改使用端口，修改app.js此段代码即可
const port = process.env.PORT || 3000
const host = process.env.HOST || ''

app.server = app.listen(port, host, () => {
  console.log(`server running @ http://${host ? host : 'localhost'}:${port}`)
})

**Comment by Red-Asuka** [comment]
> 我在本地的mac上面可以跑起来，但是在阿里云的centos上面就失败了

你好，我是直接使用node起的服务，首先将前端项目打包
根据https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/app.js 的app.js中有一段代码
// static
app.use(express.static(path.join(__dirname, 'public')))
将打包好的文件放入public文件夹下，使用forever或者pm2后台持久运行node服务
如需更改使用端口，修改app.js此段代码即可
const port = process.env.PORT || 3000
const host = process.env.HOST || ''

app.server = app.listen(port, host, () => {
console.log(server running @ http://${host ? host : 'localhost'}:${port})
})
